//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrereslaAplicacionWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int idCliente { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string Observaciones { get; set; }
        public bool Habilitado { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    }
}
